-Probably in urllib3
Exception in thread Thread-88:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/home/daniel/media/code/tcrawler/lib/threads.py", line 37, in run
    resp_item = self.agent.fetch(qitem)
  File "/home/daniel/media/code/tcrawler/lib/agent.py", line 80, in fetch
    return self.fetch(qitem)
  File "/home/daniel/media/code/tcrawler/lib/agent.py", line 66, in fetch
    resp = pool.get_url(qitem.url, retries=self.max_retry, redirect=False)
  File "/usr/local/lib/python2.6/dist-packages/urllib3-0.3-py2.6.egg/urllib3/connectionpool.py", line 231, in get_url
    return self.urlopen('GET', url, headers=headers, retries=retries, redirect=redirect)
  File "/usr/local/lib/python2.6/dist-packages/urllib3-0.3-py2.6.egg/urllib3/connectionpool.py", line 190, in urlopen
    conn = self._get_conn()
  File "/usr/local/lib/python2.6/dist-packages/urllib3-0.3-py2.6.egg/urllib3/connectionpool.py", line 137, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python2.6/dist-packages/urllib3-0.3-py2.6.egg/urllib3/connectionpool.py", line 124, in _new_conn
    return HTTPConnection(host=self.host, port=self.port)
  File "/usr/lib/python2.6/httplib.py", line 656, in __init__
    self._set_hostport(host, port)
  File "/usr/lib/python2.6/httplib.py", line 667, in _set_hostport
    i = host.rfind(':')
AttributeError: 'NoneType' object has no attribute 'rfind'


